stages:
  - lint
  - test
  - links

variables:
  CARGO_TERM_COLOR: "always"
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

.cargo-cache: &cargo-cache
  cache:
    key:
      files:
        - Cargo.lock
    paths:
      - target/
      - .cargo/registry/
      - .cargo/git/

lint:rustfmt_clippy:
  stage: lint
  image: clux/muslrust:stable
  <<: *cargo-cache
  script:
    - rustup component add rustfmt clippy
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D warnings

test:cargo:
  stage: test
  image: rust:slim-bookworm
  <<: *cargo-cache
  needs: ["lint:rustfmt_clippy"]
  script:
    - cargo test --all --locked

links:specs:
  stage: links
  image: lycheeverse/lychee:latest
  entrypoint: [""]
  script:
    - lychee --no-config --verbose --no-progress specs/
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
 
